# NumPy Tutorial
__By Anish Sachdeva__

In [2]:
# pip install numpy
import numpy as np

## The Basics

In [3]:
a = [1, 2, 3]
print(a)
print(type(a))

[1, 2, 3]
<class 'list'>


In [12]:
a = np.array(a)
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [5]:
# We can also create arrays of different dimensions in numpy
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [6]:
print(type(b))

<class 'numpy.ndarray'>


In [7]:
# we can see the dimension of any numpy array using the .shape command
print(b.shape)

(2, 3)


In [8]:
a = np.array([1, 2, 3])
print(a.shape)

(3,)


## Creating arrays using `Numpy.random` package

In [29]:
np.random.seed(10)
r = np.random.randint(100, size=(4, 10))
print(r)

[[ 9 15 64 28 89 93 29  8 73  0]
 [40 36 16 11 54 88 62 33 72 78]
 [49 51 54 77 69 13 25 13 92 86]
 [30 30 89 12 65 31 57 36 27 18]]


In [41]:
r2 = np.random.rand(3, 4)
print(r2)

[[0.44524562 0.04426012 0.24749552 0.46513333]
 [0.88291734 0.1809206  0.35617448 0.3049914 ]
 [0.72609875 0.26811569 0.34519581 0.35372182]]


## Accessing Specific Elements

In [42]:
r = np.random.randint(10, size=(3, 4))
print(r)

[[3 9 6 9]
 [7 8 0 9]
 [6 0 1 0]]


In [43]:
# accessing first row
print(r[0, :])

[3 9 6 9]


In [44]:
# accessing last row
print(r[-1, :])

[6 0 1 0]


In [45]:
# accessing specific row
row = 2
print(r[row - 1, ])

[7 8 0 9]


In [46]:
# accessing the first column
print(r[:, 0])

[3 7 6]


In [48]:
# accessing the first column and reshaping it into a column vector
c1 = r[:, 0]
print(c1)
c1 = c1.reshape((3, 1))
print(c1)

[3 7 6]
[[3]
 [7]
 [6]]


In [52]:
# accessing the last column
c2 = r[:, -1]
print(c2)

[9 9 0]


In [53]:
# reshaping the last column into column vector
c2 = c2.reshape((3, 1))
print(c2)

[[9]
 [9]
 [0]]


In [58]:
# retreiving specific rows
np.random.seed(10)
r = np.random.randint(low=0, high=100, size=(5, 6))
print(r)

[[ 9 15 64 28 89 93]
 [29  8 73  0 40 36]
 [16 11 54 88 62 33]
 [72 78 49 51 54 77]
 [69 13 25 13 92 86]]


In [61]:
print(r[[0, 1], :])

[[ 9 15 64 28 89 93]
 [29  8 73  0 40 36]]


In [62]:
# printing selected rows
print(r[[0, 3], ])

[[ 9 15 64 28 89 93]
 [72 78 49 51 54 77]]


In [63]:
# changing order of rows
print(r[[3, 0, 4], ])

[[72 78 49 51 54 77]
 [ 9 15 64 28 89 93]
 [69 13 25 13 92 86]]


In [64]:
# getting specific columns
print(r[:, [4, 2]])

[[89 64]
 [40 73]
 [62 54]
 [54 49]
 [92 25]]


In [65]:
# selecting a specific element (row, column)
print(r[0, 0])

9


In [66]:
row, column = 2, 3
print(r[row, column])

88


Getting elements using start, stop, step size (getting crazy 🙃) 

In [67]:
print(r)

[[ 9 15 64 28 89 93]
 [29  8 73  0 40 36]
 [16 11 54 88 62 33]
 [72 78 49 51 54 77]
 [69 13 25 13 92 86]]


In [68]:
print(r[::2, :])

[[ 9 15 64 28 89 93]
 [16 11 54 88 62 33]
 [69 13 25 13 92 86]]


In [69]:
print(r[::-1, ])

[[69 13 25 13 92 86]
 [72 78 49 51 54 77]
 [16 11 54 88 62 33]
 [29  8 73  0 40 36]
 [ 9 15 64 28 89 93]]


In [70]:
print(r[::-1, ::-1])

[[86 92 13 25 13 69]
 [77 54 51 49 78 72]
 [33 62 88 54 11 16]
 [36 40  0 73  8 29]
 [93 89 28 64 15  9]]


In [71]:
print(r[1:4:2, 0:5:3])
# 1, 3  |  0, 3

[[29  0]
 [72 51]]


## Changing the Value of the matrices

In [72]:
print(r)

[[ 9 15 64 28 89 93]
 [29  8 73  0 40 36]
 [16 11 54 88 62 33]
 [72 78 49 51 54 77]
 [69 13 25 13 92 86]]


In [73]:
#changing the value of a single element
r[0, 0] = 100
print(r)

[[100  15  64  28  89  93]
 [ 29   8  73   0  40  36]
 [ 16  11  54  88  62  33]
 [ 72  78  49  51  54  77]
 [ 69  13  25  13  92  86]]


In [104]:
r[0, :]

array([ -46,  -66, -105,  -23,  -12,  -85])

In [106]:
# changing the value of an entire row
r[0, :] = np.random.randint(low=-100, high=0, size=(1, 6))
print(r)

[[ -28  -72  -70  -11  -75  -22]
 [  29    8 -157    0   40   36]
 [  16   11 -112   88   62   33]
 [  72   78 -104   51   54   77]
 [  69   13 -127   13   92   86]]


In [93]:
r[:, 2]

array([-116, -118, -186, -149, -121])

In [112]:
# changing the value of an entire column 
r[:, 2] = np.random.randint(low=-200, high=-100, size=(5,))
print(r)

[[ -28  -72 -191  -11  -75  -22]
 [  29    8 -198    0   40   36]
 [  16   11 -135   88   62   33]
 [  72   78 -187   51   54   77]
 [  69   13 -125   13   92   86]]


In [114]:
# changing the value of some particular elements
r[1, [0, 2]] = 0
print(r)

[[ -28  -72 -191  -11  -75  -22]
 [   0    8    0    0   40   36]
 [  16   11 -135   88   62   33]
 [  72   78 -187   51   54   77]
 [  69   13 -125   13   92   86]]


In [116]:
k = r.copy()
k

array([[ -28,  -72, -191,  -11,  -75,  -22],
       [   0,    8,    0,    0,   40,   36],
       [  16,   11, -135,   88,   62,   33],
       [  72,   78, -187,   51,   54,   77],
       [  69,   13, -125,   13,   92,   86]])

In [118]:
# broadcasting
k[0, :] = 100
k

array([[ 100,  100,  100,  100,  100,  100],
       [   0,    8,    0,    0,   40,   36],
       [  16,   11, -135,   88,   62,   33],
       [  72,   78, -187,   51,   54,   77],
       [  69,   13, -125,   13,   92,   86]])

In [119]:
k[:, 0] = -100
k

array([[-100,  100,  100,  100,  100,  100],
       [-100,    8,    0,    0,   40,   36],
       [-100,   11, -135,   88,   62,   33],
       [-100,   78, -187,   51,   54,   77],
       [-100,   13, -125,   13,   92,   86]])

In [124]:
k[1:4:2, [0, 4]] = -50
k

array([[-100,  100,  100,  100,  100,  100],
       [ -50,    8,    0,    0,  -50,   36],
       [-100,   11, -135,   88,   62,   33],
       [ -50,   78, -187,   51,  -50,   77],
       [-100,   13, -125,   13,   92,   86]])

In [127]:
k[0:3:2, [3, 4]]

array([[100, 100],
       [ 88,  62]])

## Different Initialization Methods

In [128]:
# Creating the zeros Matrix
z = np.zeros((3, 3))
print(z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [129]:
z = np.zeros((3, 4))
print(z)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [131]:
# creating matrix with data type defined as int
z = np.zeros((3, 4), dtype=np.int)
print(z)
print(z.dtype)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
int32


In [132]:
# creating all 1's matrix
o = np.ones((2, 4))
print(o)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [133]:
o = np.ones((2, 4), dtype=np.int)
print(o)

[[1 1 1 1]
 [1 1 1 1]]


In [136]:
# creating a matrix with some arbitrary number
f = np.full(shape=(3, 4), fill_value=-98)
print(f)
print(f.dtype)

[[-98 -98 -98 -98]
 [-98 -98 -98 -98]
 [-98 -98 -98 -98]]
int32


In [137]:
f = np.full(shape=(1, 2), fill_value=2.0)
print(f)
print(f.dtype)

[[2. 2.]]
float64


In [138]:
# The Identity Matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [139]:
np.identity(5, dtype=np.int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [140]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Creating copy of Arrays

In [141]:
a = np.array([1, 2, 3])
b = a
b[0] = 100
print(a)

[100   2   3]


In [142]:
a = np.array([1, 2, 3])
b = a.copy()
b[0] = 100
print(a)

[1 2 3]


## Broadcasting in NumPy Arrays

In [90]:
a = [1, 2, 3]
print(type(a))
print(a + 1)

<class 'list'>


TypeError: can only concatenate list (not "int") to list

In [143]:
a = np.array([1, 2, 3])
print(a + 1)

[2 3 4]


In [144]:
np.random.randint(low=0, high=100, size=(4, 5)) - 50

array([[  2, -45,  43,  34,  -2],
       [ 12,  -8, -16, -10,  -4],
       [-18,  44,  36,   8,  19],
       [ -5, -32,   0,  -6, -49]])

## Basic Mathematicall Operations 

In [145]:
# Multilication with scalar
np.random.seed(10)
A = np.random.randint(0, 100, size=(3, 4))
print(A)

[[ 9 15 64 28]
 [89 93 29  8]
 [73  0 40 36]]


In [146]:
A * 0

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [80]:
4 * A

array([[ 36,  60, 256, 112],
       [356, 372, 116,  32],
       [292,   0, 160, 144]])

In [147]:
# Division with scalar
A / 2

array([[ 4.5,  7.5, 32. , 14. ],
       [44.5, 46.5, 14.5,  4. ],
       [36.5,  0. , 20. , 18. ]])

In [148]:
A // 3

array([[ 3,  5, 21,  9],
       [29, 31,  9,  2],
       [24,  0, 13, 12]], dtype=int32)

In [102]:
A / np.array([1, 2, 3, 4])

array([[ 9.        ,  7.5       , 21.33333333,  7.        ],
       [89.        , 46.5       ,  9.66666667,  2.        ],
       [73.        ,  0.        , 13.33333333,  9.        ]])

In [149]:
B = np.random.randint(1, 5, size=(3, 4))
B

array([[4, 1, 1, 4],
       [4, 3, 1, 4],
       [3, 3, 2, 1]])

In [151]:
A

array([[ 9, 15, 64, 28],
       [89, 93, 29,  8],
       [73,  0, 40, 36]])

In [150]:
A / B

array([[ 2.25      , 15.        , 64.        ,  7.        ],
       [22.25      , 31.        , 29.        ,  2.        ],
       [24.33333333,  0.        , 20.        , 36.        ]])

In [104]:
A / np.random.randint(1, 5, size=(3, 4))

array([[ 2.25      , 15.        , 64.        ,  7.        ],
       [22.25      , 31.        , 29.        ,  2.        ],
       [24.33333333,  0.        , 20.        , 36.        ]])

## Matrix Operations

In [153]:
type(A)

numpy.ndarray

In [152]:
A = np.random.randint(1, 20, size=(2, 3))
print(A)

[[ 5 15 18]
 [14  6 14]]


In [154]:
B = np.random.randint(1, 20, size=(2, 3))
print(B)

[[14 13  2]
 [ 5 19 14]]


In [155]:
A + B

array([[19, 28, 20],
       [19, 25, 28]])

In [156]:
A + 2 * B

array([[33, 41, 22],
       [24, 44, 42]])

In [157]:
A - B

array([[ -9,   2,  16],
       [  9, -13,   0]])

## Element wise Operations

In [158]:
print(A)

[[ 5 15 18]
 [14  6 14]]


In [159]:
# element wise power operator
A ** 2

array([[ 25, 225, 324],
       [196,  36, 196]], dtype=int32)

In [160]:
np.sin(A)

array([[-0.95892427,  0.65028784, -0.75098725],
       [ 0.99060736, -0.2794155 ,  0.99060736]])

In [161]:
np.cos(A)

array([[ 0.28366219, -0.75968791,  0.66031671],
       [ 0.13673722,  0.96017029,  0.13673722]])

In [162]:
np.tan(A)

array([[-3.38051501, -0.8559934 , -1.13731371],
       [ 7.24460662, -0.29100619,  7.24460662]])

In [163]:
np.exp(A)

array([[1.48413159e+02, 3.26901737e+06, 6.56599691e+07],
       [1.20260428e+06, 4.03428793e+02, 1.20260428e+06]])

## Linear Algebra

In [164]:
# Taking the matrix dot products between 2 matrices
A = np.array([[1, 2]])
B = np.array([[5, 10, 0], [-9, 0, 3]])

In [165]:
print(A)

[[1 2]]


In [166]:
print(B)

[[ 5 10  0]
 [-9  0  3]]


In [167]:
A.shape

(1, 2)

In [168]:
B.shape

(2, 3)

In [169]:
R = A.dot(B)
print(R)

[[-13  10   6]]


In [170]:
R.shape

(1, 3)

## Important

$dim A$ = ($n_1$, $m_1$)

$dim B$ = ($n_2$, $m_2$)

if $m_1 = n_2$

$$(n_1, m_2)$$

In [97]:
print(A.shape)
print(B.shape)
print(R.shape)

(1, 2)
(2, 3)
(1, 3)


In [171]:
# Determinant of a Square Matrix
A = np.random.randint(-100, 100, size=(4, 4))
print(A)

[[ 50  51  -6  39]
 [ 56 -26  37 -85]
 [-82  18 -29 -12]
 [ 39  45  74  35]]


In [172]:
print(np.linalg.det(A))

-35452169.000000015


In [173]:
I = np.identity(4, dtype=np.int)
print(I)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [174]:
print(np.linalg.det(I))

1.0


In [175]:
# Find the Trace of a Square Matrix
print(A)

[[ 50  51  -6  39]
 [ 56 -26  37 -85]
 [-82  18 -29 -12]
 [ 39  45  74  35]]


In [176]:
print(np.trace(A))

30


In [177]:
print(np.trace(I))

4


In [178]:
# calculating the inverse of a matrix
np.linalg.inv(I)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [179]:
A_inv = np.linalg.inv(A)
print(A_inv)

[[ 0.0074504   0.00291621 -0.00745664 -0.00377621]
 [ 0.0141432   0.0060167   0.01456156  0.00384496]
 [-0.01061678  0.000274   -0.00041044  0.01235484]
 [-0.00403908 -0.01156457 -0.0095454   0.00171403]]


In [199]:
K = np.arange(9).reshape(3, 3)
K

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [200]:
np.linalg.det(K)

0.0

In [201]:
np.linalg.inv(K)

LinAlgError: Singular matrix

In [180]:
print(A.dot(A_inv))

[[ 1.00000000e+00 -4.68375339e-17 -5.55111512e-17 -4.29344060e-17]
 [ 7.11236625e-17  1.00000000e+00 -1.11022302e-16 -3.77302356e-17]
 [ 1.38777878e-17 -6.93889390e-18  1.00000000e+00 -2.25514052e-17]
 [-1.09287579e-16 -1.21430643e-17  0.00000000e+00  1.00000000e+00]]


In [181]:
print(A_inv.dot(A))

[[ 1.00000000e+00 -9.28077060e-17 -3.29597460e-17 -5.98479599e-17]
 [-1.30537942e-16  1.00000000e+00 -1.99493200e-17 -4.33680869e-19]
 [ 5.72458747e-17  1.90819582e-17  1.00000000e+00  8.67361738e-18]
 [-1.30104261e-18  1.34441069e-17  6.07153217e-18  1.00000000e+00]]


In [183]:
J = A.dot(A_inv)
print(J)

[[ 1.00000000e+00 -4.68375339e-17 -5.55111512e-17 -4.29344060e-17]
 [ 7.11236625e-17  1.00000000e+00 -1.11022302e-16 -3.77302356e-17]
 [ 1.38777878e-17 -6.93889390e-18  1.00000000e+00 -2.25514052e-17]
 [-1.09287579e-16 -1.21430643e-17  0.00000000e+00  1.00000000e+00]]


In [185]:
mask = np.array(J > 10 ** -10, dtype=np.int)
mask

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [187]:
mask2 = np.array([
    [1, 1, 1, 1],
    [0, 0, 0, 0],
    [0.5, 0.5, 0.5, 0.5],
    [0, 0, 0, 0]
])
mask2

array([[1. , 1. , 1. , 1. ],
       [0. , 0. , 0. , 0. ],
       [0.5, 0.5, 0.5, 0.5],
       [0. , 0. , 0. , 0. ]])

In [189]:
A * mask2

array([[ 50. ,  51. ,  -6. ,  39. ],
       [  0. ,  -0. ,   0. ,  -0. ],
       [-41. ,   9. , -14.5,  -6. ],
       [  0. ,   0. ,   0. ,   0. ]])

In [186]:
mask * J

array([[ 1., -0., -0., -0.],
       [ 0.,  1., -0., -0.],
       [ 0., -0.,  1., -0.],
       [-0., -0.,  0.,  1.]])

In [193]:
# thresholding
mask_3 = np.array(A > 10, dtype=np.int)
mask_3

array([[1, 1, 0, 1],
       [1, 0, 1, 0],
       [0, 1, 0, 0],
       [1, 1, 1, 1]])

In [194]:
A * mask_3

array([[50, 51,  0, 39],
       [56,  0, 37,  0],
       [ 0, 18,  0,  0],
       [39, 45, 74, 35]])

In [195]:
# finding the transpose of a matrix
B = np.arange(6).reshape(2, 3)
print(B)

[[0 1 2]
 [3 4 5]]


In [196]:
print(B.shape)

(2, 3)


In [198]:
print(B.T)
print(B.T.shape)

[[0 3]
 [1 4]
 [2 5]]
(3, 2)


In [202]:
J = np.array([[1, 2,3, 4, 5]])
J

array([[1, 2, 3, 4, 5]])

In [203]:
J.shape

(1, 5)

In [206]:
J.T

array([[1],
       [2],
       [3],
       [4],
       [5]])

## Statistics

In [207]:
print(A)

[[ 50  51  -6  39]
 [ 56 -26  37 -85]
 [-82  18 -29 -12]
 [ 39  45  74  35]]


In [209]:
# finding minimum in the matrix
np.min(A)

-85

In [210]:
# finding minimum in every column vector
np.min(A, axis=0)

array([-82, -26, -29, -85])

In [211]:
# finding the mimimum in every row vector
np.min(A, axis=1)

array([ -6, -85, -82,  35])

In [212]:
# finding maximum in entire matrix
print(np.max(A))

74


In [213]:
# finding maximum in every column vector 
np.max(A, axis=0)

array([56, 51, 74, 39])

In [158]:
# finding the maximum in every row vector
np.max(A, axis=1)

array([12, 85, -3, 68])

In [215]:
# sum of every element in the matrix
np.sum(A)

204

In [217]:
# sum of elements in every column vector
np.sum(A, axis=0)

array([ 63,  88,  76, -23])

In [218]:
# sum of elements in every row vector
np.sum(A, axis=1)

204

In [224]:
A.sum(axis=1)

array([ 134,  -18, -105,  193])

## Boolean Operations on Arrays

In [225]:
A = np.arange(35).reshape(5, 7)
print(A)

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]]


In [226]:
# equality check
A == 4

array([[False, False, False, False,  True, False, False],
       [False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False]])

In [227]:
# comparison operator
A < 10

array([[ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True, False, False, False, False],
       [False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False]])

In [228]:
A >= 23

array([[False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [False, False,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True]])

In [229]:
# converting a boolean array to integer array
(A < 20).astype(np.int)

array([[1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])