# NumPy Tutorial
__By Anish Sachdeva__

In [10]:
# pip install numpy
import numpy as np

## The Basics

In [11]:
a = [1, 2, 3]
print(a)
print(type(a))

[1, 2, 3]
<class 'list'>


In [12]:
a = np.array(a)
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [13]:
# We can also create arrays of different dimensions in numpy
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [14]:
print(type(b))

<class 'numpy.ndarray'>


In [15]:
# we can see the dimension of any numpy array using the .shape command
print(b.shape)

(2, 3)


In [16]:
a = np.array([1, 2, 3])
print(a.shape)

(3,)


## Creating arrays using `Numpy.random` package

In [23]:
r = np.random.randint(100, size=(4, 10))
print(r)

[[40 75 46 87 52 62 63 10 63 18]
 [95 92 71 27 25 60 13 50 96  1]
 [ 8 26 16 32 24 19 53 78 93 33]
 [76  0 72 61 75 30 67 87 32 76]]


In [29]:
r2 = np.random.rand(3, 4)
print(r2)

[[0.57840171 0.09462694 0.67157189 0.09640049]
 [0.63757744 0.83297213 0.00805271 0.50300539]
 [0.69773873 0.67494469 0.10092988 0.45283268]]


## Accessing Specific Elements

In [31]:
r = np.random.randint(10, size=(3, 4))
print(r)

[[7 0 3 8]
 [6 8 6 6]
 [3 6 4 4]]


In [32]:
# accessing first row
print(r[0, :])

[7 0 3 8]


In [33]:
# accessing last row
print(r[-1, :])

[3 6 4 4]


In [34]:
# accessing specific row
row = 2
print(r[row - 1, ])

[6 8 6 6]


In [35]:
# accessing the first column
print(r[:, 0])

[7 6 3]


In [36]:
# accessing the last column and reshaping it into a column vector
c1 = r[:, 0]
print(c1)
c1 = c1.reshape((3, 1))
print(c1)

[7 6 3]
[[7]
 [6]
 [3]]


In [37]:
# accessing the last column
c2 = r[:, -1]
print(c2)

[8 6 4]


In [38]:
# reshaping the last column into column vector
c2 = c2.reshape((3, 1))
print(c2)

[[8]
 [6]
 [4]]


In [49]:
# retreiving specific rows
np.random.seed(10)
r = np.random.randint(low=0, high=100, size=(5, 6))
print(r)

[[ 9 15 64 28 89 93]
 [29  8 73  0 40 36]
 [16 11 54 88 62 33]
 [72 78 49 51 54 77]
 [69 13 25 13 92 86]]


In [50]:
print(r[[0, 1], :])

[[ 9 15 64 28 89 93]
 [29  8 73  0 40 36]]


In [51]:
# printing selected rows
print(r[[0, 3], ])

[[ 9 15 64 28 89 93]
 [72 78 49 51 54 77]]


In [52]:
# changing order of rows
print(r[[3, 0, 4], ])

[[72 78 49 51 54 77]
 [ 9 15 64 28 89 93]
 [69 13 25 13 92 86]]


In [53]:
# getting specific columns
print(r[:, [4, 2]])

[[89 64]
 [40 73]
 [62 54]
 [54 49]
 [92 25]]


In [54]:
# selecting a specific element (row, column)
print(r[0, 0])

9


In [55]:
row, column = 2, 3
print(r[row, column])

88


Getting elements using start, stop, step size (getting crazy 🙃) 

In [56]:
print(r)

[[ 9 15 64 28 89 93]
 [29  8 73  0 40 36]
 [16 11 54 88 62 33]
 [72 78 49 51 54 77]
 [69 13 25 13 92 86]]


In [57]:
print(r[::2, :])

[[ 9 15 64 28 89 93]
 [16 11 54 88 62 33]
 [69 13 25 13 92 86]]


In [58]:
print(r[::-1, ])

[[69 13 25 13 92 86]
 [72 78 49 51 54 77]
 [16 11 54 88 62 33]
 [29  8 73  0 40 36]
 [ 9 15 64 28 89 93]]


In [59]:
print(r[::-1, ::-1])

[[86 92 13 25 13 69]
 [77 54 51 49 78 72]
 [33 62 88 54 11 16]
 [36 40  0 73  8 29]
 [93 89 28 64 15  9]]


In [60]:
print(r[1:4:2, 0:5:3])

[[29  0]
 [72 51]]


## Changing the Value of the matrices

In [61]:
print(r)

[[ 9 15 64 28 89 93]
 [29  8 73  0 40 36]
 [16 11 54 88 62 33]
 [72 78 49 51 54 77]
 [69 13 25 13 92 86]]


In [62]:
#changing the value of a single element
r[0, 0] = 100
print(r)

[[100  15  64  28  89  93]
 [ 29   8  73   0  40  36]
 [ 16  11  54  88  62  33]
 [ 72  78  49  51  54  77]
 [ 69  13  25  13  92  86]]


In [63]:
# changing the value of an entire row
r[0, :] = np.random.randint(low=-100, high=0, size=(1, 6))
print(r)

[[-70 -70 -11 -88 -35 -69]
 [ 29   8  73   0  40  36]
 [ 16  11  54  88  62  33]
 [ 72  78  49  51  54  77]
 [ 69  13  25  13  92  86]]


In [64]:
# changing the value of an entire column 
r[:, [2]] = np.random.randint(low=-200, high=-100, size=(5, 1))
print(r)

[[ -70  -70 -143  -88  -35  -69]
 [  29    8 -164    0   40   36]
 [  16   11 -173   88   62   33]
 [  72   78 -182   51   54   77]
 [  69   13 -107   13   92   86]]


In [65]:
# changing the value of some particular elements
r[1, [0, 2]] = [0, 0]
print(r)

[[ -70  -70 -143  -88  -35  -69]
 [   0    8    0    0   40   36]
 [  16   11 -173   88   62   33]
 [  72   78 -182   51   54   77]
 [  69   13 -107   13   92   86]]


## Different Initialization Methods

In [66]:
# Creating the zeros Matrix
z = np.zeros((3, 3))
print(z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [67]:
z = np.zeros((3, 4))
print(z)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [68]:
# creating matrix with data type defined as int
z = np.zeros((3, 4), dtype=np.int)
print(z)
print(z.dtype)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
int32


In [69]:
# creating all 1's matrix
o = np.ones((2, 4))
print(o)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [70]:
o = np.ones((2, 4), dtype=np.int)
print(o)

[[1 1 1 1]
 [1 1 1 1]]


In [71]:
# creating a matrix with some arbitrary number
f = np.full(shape=(3, 4), fill_value=100)
print(f)
print(f.dtype)

[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]]
int32


In [72]:
f = np.full(shape=(1, 2), fill_value=2.0)
print(f)
print(f.dtype)

[[2. 2.]]
float64


In [73]:
# The Identity Matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [74]:
np.identity(5, dtype=np.int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

## Creating copy of Arrays

In [75]:
a = np.array([1, 2, 3])
b = a
b[0] = 100
print(a)

[100   2   3]


In [86]:
a = np.array([1, 2, 3])
b = a.copy()
b[0] = 100
print(a)

[1 2 3]


## Broadcasting in NumPy Arrays

In [90]:
a = [1, 2, 3]
print(type(a))
print(a + 1)

<class 'list'>


TypeError: can only concatenate list (not "int") to list

In [76]:
a = np.array([1, 2, 3])
print(a + 1)

[2 3 4]


In [77]:
np.random.randint(0, 100, size=(4, 5)) - 50

array([[ 27, -28, -27,  44, -39],
       [-22,  24,  38, -41, -35],
       [-32,  30,  21,  38, -39],
       [-33,  -4, -43,  25, -22]])

## Basic Mathematicall Operations 

In [78]:
# Multilication with scalar
np.random.seed(10)
A = np.random.randint(0, 100, size=(3, 4))
print(A)

[[ 9 15 64 28]
 [89 93 29  8]
 [73  0 40 36]]


In [79]:
A * 0

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [80]:
4 * A

array([[ 36,  60, 256, 112],
       [356, 372, 116,  32],
       [292,   0, 160, 144]])

In [81]:
# Division with scalar
A / 2

array([[ 4.5,  7.5, 32. , 14. ],
       [44.5, 46.5, 14.5,  4. ],
       [36.5,  0. , 20. , 18. ]])

In [82]:
A // 3

array([[ 3,  5, 21,  9],
       [29, 31,  9,  2],
       [24,  0, 13, 12]], dtype=int32)

In [102]:
A / np.array([1, 2, 3, 4])

array([[ 9.        ,  7.5       , 21.33333333,  7.        ],
       [89.        , 46.5       ,  9.66666667,  2.        ],
       [73.        ,  0.        , 13.33333333,  9.        ]])

In [104]:
A / np.random.randint(1, 5, size=(3, 4))

array([[ 2.25      , 15.        , 64.        ,  7.        ],
       [22.25      , 31.        , 29.        ,  2.        ],
       [24.33333333,  0.        , 20.        , 36.        ]])

## Matrix Operations

In [83]:
A = np.random.randint(1, 20, size=(2, 3))
print(A)

[[17  5 16]
 [12 12  2]]


In [84]:
B = np.random.randint(1, 20, size=(2, 3))
print(B)

[[ 9  5 15]
 [18 14  6]]


In [85]:
A + B

array([[26, 10, 31],
       [30, 26,  8]])

In [86]:
A + 2 * B

array([[35, 15, 46],
       [48, 40, 14]])

In [87]:
A - B

array([[ 8,  0,  1],
       [-6, -2, -4]])

## Element wise Operations

In [88]:
print(A)

[[17  5 16]
 [12 12  2]]


In [89]:
# element wise power operator
A ** 2

array([[289,  25, 256],
       [144, 144,   4]], dtype=int32)

In [90]:
np.sin(A)

array([[-0.96139749, -0.95892427, -0.28790332],
       [-0.53657292, -0.53657292,  0.90929743]])

In [91]:
np.cos(A)

array([[-0.27516334,  0.28366219, -0.95765948],
       [ 0.84385396,  0.84385396, -0.41614684]])

In [92]:
np.tan(A)

array([[ 3.49391565, -3.38051501,  0.30063224],
       [-0.63585993, -0.63585993, -2.18503986]])

In [116]:
np.exp(A)

array([[1.48413159e+02, 3.26901737e+06, 6.56599691e+07],
       [1.20260428e+06, 4.03428793e+02, 1.20260428e+06]])

## Linear Algebra

In [93]:
# Taking the matrix dot products between 2 matrices
A = np.array([[1, 2]])
B = np.array([[5, 10, 0], [-9, 0, 3]])

In [94]:
print(A)

[[1 2]]


In [95]:
print(B)

[[ 5 10  0]
 [-9  0  3]]


In [96]:
R = A.dot(B)
print(R)

[[-13  10   6]]


## Important
(n_1, m_1) (n_2, m_2)
if m_1 == n_2

In [97]:

print(A.shape)
print(B.shape)
print(R.shape)

(1, 2)
(2, 3)
(1, 3)


In [98]:
# Determinant of a Square Matrix
A = np.random.randint(-100, 100, size=(4, 4))
print(A)

[[-87  53  26  41]
 [ -8 -14 -70  58]
 [-11  40 -35 -69]
 [-43 -64 -73 -82]]


In [99]:
print(np.linalg.det(A))

89338731.99999985


In [100]:
I = np.identity(4, dtype=np.int)
print(I)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [101]:
print(np.linalg.det(I))

1.0


In [102]:
# Find the Trace of a Square Matrix
print(A)

[[-87  53  26  41]
 [ -8 -14 -70  58]
 [-11  40 -35 -69]
 [-43 -64 -73 -82]]


In [103]:
print(np.trace(A))

-218


In [104]:
print(np.trace(I))

4


In [105]:
# calculating the inverse of a matrix
np.linalg.inv(I)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [106]:
A_inv = np.linalg.inv(A)
print(A_inv)

[[-0.00904045  0.00141389  0.00291569 -0.0059736 ]
 [ 0.0018797   0.00238908  0.01174299 -0.00725161]
 [ 0.00193925 -0.00983203 -0.00664281 -0.00039506]
 [ 0.00154723  0.00614683 -0.0047805  -0.00305113]]


In [107]:
print(A.dot(A_inv))

[[ 1.00000000e+00 -8.67361738e-18 -1.56125113e-17  8.67361738e-19]
 [ 7.80625564e-18  1.00000000e+00  6.59194921e-17 -4.68375339e-17]
 [-4.33680869e-19  8.50014503e-17  1.00000000e+00 -2.51534904e-17]
 [ 9.54097912e-18 -9.36750677e-17  8.67361738e-17  1.00000000e+00]]


In [108]:
print(A_inv.dot(A))

[[ 1.00000000e+00  1.11022302e-16 -2.68882139e-17  1.12757026e-16]
 [-9.54097912e-18  1.00000000e+00  1.99493200e-17  9.54097912e-17]
 [ 2.30935063e-17 -6.93889390e-17  1.00000000e+00 -2.97071395e-17]
 [ 1.12757026e-17  2.77555756e-17 -8.67361738e-19  1.00000000e+00]]


In [110]:
# finding the transpose of a matrix
B = np.arange(6).reshape(2, 3)
print(B)

[[0 1 2]
 [3 4 5]]


In [111]:
print(B.shape)

(2, 3)


In [112]:
print(B.T)
print(B.T.shape)

[[0 3]
 [1 4]
 [2 5]]
(3, 2)


## Statistics

In [113]:
print(A)

[[-87  53  26  41]
 [ -8 -14 -70  58]
 [-11  40 -35 -69]
 [-43 -64 -73 -82]]


In [114]:
# finding minimum in the matrix
np.min(A)

-87

In [115]:
# finding minimum in every column vector
np.min(A, axis=0)

array([-87, -64, -73, -82])

In [116]:
# finding the mimimum in every row vector
np.min(A, axis=1)

array([-87, -70, -69, -82])

In [156]:
# finding maximum in entire matrix
print(np.max(A))

85


In [159]:
# finding maximum in every column vector 
np.max(A, axis=0)

array([85, 65, 28, 46])

In [158]:
# finding the maximum in every row vector
np.max(A, axis=1)

array([12, 85, -3, 68])

In [160]:
# sum of every element in the matrix
np.sum(A)

-133

In [161]:
# sum of elements in every column vector
np.sum(A, axis=0)

array([  21,   53, -102, -105])

In [163]:
# sum of elements in every row vector
np.sum(A, axis=1)

array([-203,   14, -151,  207])

## Boolean Operations on Arrays

In [117]:
A = np.arange(35).reshape(5, 7)
print(A)

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]]


In [118]:
# equality check
A == 4

array([[False, False, False, False,  True, False, False],
       [False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False]])

In [119]:
# comparison operator
A < 10

array([[ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True, False, False, False, False],
       [False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False]])

In [120]:
A >= 23

array([[False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [False, False,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True]])

In [121]:
# converting a boolean array to integer array
(A < 20).astype(np.int)

array([[1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])